### ISSUE TITLE
Cooldowns do not appear to be working... am I doing something wrong?

### ISSUE THREAD

**Issue by VULTVR3** [AlexPads/KitsPlus#4]
```
Kits:
  Guest:
    Cost: 0
    Permission: "kit.guest"
    KitFormName: "§l§7Ｇｕｅｓｔ §8Ｋｉｔ"
    KitChestName: "§l§7Ｇｕｅｓｔ §8Ｋｉｔ§r"
    Helmet: "306:0:1:§l§7Ｇｕｅｓｔ §6Ｇｅａｒ:0:5:17:10"
    Chestplate: "307:0:1:§l§7Ｇｕｅｓｔ §6Ｇｅａｒ:0:5:17:10"
    Leggings: "308:0:1:§l§7Ｇｕｅｓｔ §6Ｇｅａｒ:0:5:17:10"
    Boots: "309:0:1:§l§7Ｇｕｅｓｔ §6Ｇｅａｒ:0:5:17:10"
    CooldownTime: 3600
    Items:
      - "257:0:1:§l§7Ｇｕｅｓｔ §6Ｓｈｏｒｔｓｗｏｒｄ:9:2:17:10"
      - "258:0:1:§l§7Ｇｕｅｓｔ §6Ａｘｅ:15:2:17:10"
      - "257:0:1:§l§7Ｇｕｅｓｔ §6Ｐｉｃｋａｘｅ:15:2:17:10"
      - "256:0:1:§l§7Ｇｕｅｓｔ §6Ｓｈｏｖｅｌ:15:2:17:10"
      - "260:0:16:default"
      - "322:0:4:default"
```

When I go to get the kit, I can do it as many times as I want with no cooldowns.
